# Generated by Django 2.2 on 2020-06-07 06:31

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
