# Generated by Django 2.2 on 2020-06-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account',
            new_name='user',
        ),
    ]
